version: "3.8"

services:
  mysql:
    image: mysql:8.0
    container_name: mysql_carsharing
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQLDB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQLDB_DATABASE}
    ports:
      - "${MYSQLDB_HOST_PORT}:${MYSQLDB_CONTAINER_PORT}"
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping" , "-h","127.0.0.1","-u","root","--password=${MYSQLDB_ROOT_PASSWORD}" ]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    depends_on:
      mysql:
        condition: service_healthy
    restart: on-failure
    build: .
    image: posts-service
    env_file: ./.env
    ports:
      - "${SPRING_HOST_PORT}:${SPRING_CONTAINER_PORT}"
      - "${DEBUG_PORT}:${DEBUG_PORT}"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql_carsharing:${MYSQLDB_CONTAINER_PORT}/${MYSQLDB_DATABASE}
      SPRING_DATASOURCE_USERNAME: ${MYSQLDB_USER}
      SPRING_DATASOURCE_PASSWORD: ${MYSQLDB_ROOT_PASSWORD}
      JAVA_TOOL_OPTIONS: "-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:${DEBUG_PORT}"